version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "12:00"
    timezone: Etc/GMT+2
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@babel/cli"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.10
  - dependency-name: npm
    versions:
    - 7.5.2
    - 7.5.3
    - 7.5.4
    - 7.5.5
    - 7.5.6
    - 7.6.0
    - 7.6.1
    - 7.6.2
    - 7.6.3
    - 7.7.0
    - 7.7.1
    - 7.7.2
    - 7.7.3
    - 7.7.4
    - 7.7.5
    - 7.7.6
  - dependency-name: "@babel/runtime-corejs3"
    versions:
    - 7.12.13
    - 7.12.17
    - 7.12.18
    - 7.13.0
    - 7.13.1
    - 7.13.4
    - 7.13.7
    - 7.13.8
    - 7.13.9
  - dependency-name: core-js
    versions:
    - 3.10.2
    - 3.11.0
    - 3.8.3
    - 3.9.0
    - 3.9.1
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
  - dependency-name: rollup
    versions:
    - 2.38.1
    - 2.38.2
    - 2.38.3
    - 2.38.4
    - 2.38.5
    - 2.39.0
    - 2.39.1
    - 2.40.0
    - 2.41.0
    - 2.41.1
    - 2.41.2
    - 2.41.4
    - 2.41.5
    - 2.42.0
    - 2.42.1
    - 2.42.2
    - 2.42.3
    - 2.42.4
    - 2.43.0
    - 2.45.2
  - dependency-name: stylelint
    versions:
    - 13.10.0
    - 13.11.0
    - 13.9.0
  - dependency-name: np
    versions:
    - 7.2.0
    - 7.3.0
  - dependency-name: "@babel/plugin-transform-arrow-functions"
    versions:
    - 7.12.13
  - dependency-name: browserslist
    versions:
    - 4.16.2
  - dependency-name: acorn
    versions:
    - 8.0.5
    - 8.1.1
    - 8.2.0
    - 8.2.1
  - dependency-name: postcss
    versions:
    - 8.2.10
    - 8.2.11
    - 8.2.12
    - 8.2.9
  - dependency-name: "@babel/plugin-transform-runtime"
    versions:
    - 7.13.10
    - 7.13.15
  - dependency-name: stylelint-config-standard
    versions:
    - 21.0.0
  - dependency-name: y18n
    versions:
    - 4.0.2
  - dependency-name: concurrently
    versions:
    - 6.0.0
